### ISSUE TITLE
Is it Possible to Use This Crate to Make an LDAP Server?

### ISSUE THREAD

**Issue by zicklag** [coder543/rust-cldap#10]
Is it possible to use this to create an app that serves the LDAP API? I want to make an app that can be queried through the LDAP protocol and therefore be compatible with any app that supports LDAP, but the app will actually backed by a non-LDAP data store.

**Comment by pwestrich** [comment]
No, this library is a thin wrapper around the C LDAP client library. It only has the functionality of the client end.

**Comment by zicklag** [comment]
OK, thanks. :+1:
