### ISSUE TITLE
Async Examples

### ISSUE THREAD

**Issue by cbass27** [coder543/rust-cldap#11]
I've been searching and can't find any async examples using rust-cldap. Could anyone provide some async examples as I'm having a difficult time getting it working. Thanks in advance.

**Comment by coder543** [comment]
I'm sorry, but this was all developed a long time ago, and isn't really maintained at the moment. Given that this is a wrapper around a C library, I don't really see how an async implementation would be possible -- the C library isn't going to be using Rust's async primitives, so the only thing someone would likely bother to do is run the LDAP calls on a separate OS thread, and you can easily do that with Tokio's `spawn_blocking`, I believe.

Really, you would need a native Rust implementation of LDAP for a true async version.
