### ISSUE TITLE
Doesn't link to ldap_r on Arch Linux

### ISSUE THREAD

**Issue by robertsarkozi** [coder543/rust-cldap#12]
Maybe this is more of an openldap question:
I have openldap installed, but the example doesn't link to ldap_r.
How do I install it?

Also, the repo from which this is forked from link to ldap, not ldap_r:
https://github.com/pwestrich/rust-cldap/blob/master/src/lib.rs#L26

The change to ldap_r happened here: https://github.com/coder543/rust-cldap/commit/cb87c3b1fdac741b97cc10f486d0b3e7f8412ab5

Thanks

**Comment by coder543** [comment]
You’re welcome to try changing it back to `ldap`. I don’t remember what happened nearly six years ago to make that change necessary.

This library is unmaintained at this point, since I haven’t had any use for LDAP in a very long time.
