### ISSUE TITLE
Update unit testing situation

### ISSUE THREAD

**Issue by JedimEmO** [coder543/rust-cldap#5]
Currently, the unit tests are not working, seeing how they are based on ldap://ldap.forumsys.com, which doesn't seem to work any more.

I will look at updating the test suite to work with https://hub.docker.com/r/rroemhild/test-openldap/ over the weekend, which will make future development feel a bit safer :)

**Comment by coder543** [comment]
I just checked on my local system, and the current test suite works fine, apart from the TLS test, which forumsys doesn’t support, so I’m not sure why you’re experiencing that.

But, if you send in a PR, I’m happy to look at it when I get a chance.

**Comment by JedimEmO** [comment]
Yeah, I had to test that against our internal LDAP. I'll put up a PR when it's operational :)

**Comment by JedimEmO** [comment]
Closing this one, I think I will leave the unit tests alone for now, and rather add some more examples
