### ISSUE TITLE
[Question] How to use this crate?

### ISSUE THREAD

**Issue by Geobert** [coder543/rust-cldap#6]
Hi,

How are we suppose to use this crate? It needs the OpenLDAP library, obviously, but I can't see how to link against the C lib here (no `build.rs` nor `rust-cldap-sys` crate to wrap the C lib).

Regards

**Comment by JedimEmO** [comment]
https://github.com/coder543/rust-cldap/blob/master/src/lib.rs#L39

I guess it assumes an openldap installation on the host system...

**Comment by coder543** [comment]
@JedimEmO is correct. If you have openldap installed correctly on your system, it will automatically link against that. “installed correctly” means that it is in the standard paths for your operating system where any normal compiler like `gcc` would be able to find it and link against it, essentially.

**Comment by Geobert** [comment]
Thank you!
